### ISSUE TITLE
Would it be worth adding a Header field to the RadarScanLine message itself?

### ISSUE THREAD

**Issue by arjo129** [CCOMJHC/marine_sensor_msgs#3]
In the past I have often found it advantageous to publish the RADAR Scan line as the RADAR update rates can be quite slow and under rotation the bitmaps retrieved are often useless. Would be nice if the header were embedded in. Or perhaps we could have a RadarScanLineStamped message.

**Comment by rolker** [comment]
Good idea. The radar I use sends multiple spokes per packet which is why I haven't added a header, but I don't see much harm as it would only add a few bytes.

**Comment by rolker** [comment]
The message has evolved such that I don't think this is still relevant.
